import "./globals.css";
import CategoryFilter from "@/app/components/Categories";
import { getFiltersData } from "@/lib/db-queries";
import Header from "./components/Header";
import { NextAuthProvider } from "./providers";
export const metadata = {
  title: "Buzz Pop Notes",
  description: "Generated by create next app",
};

interface IProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: IProps) {
  const categories = await getFiltersData();

  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <Header />
          <CategoryFilter categories={categories} />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
